name: Test CF CLI Action

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: uktrade/cf-vault-env-tool@master
      with:
        vault_url: ${{ secrets.VAULT_URL }}
        vault_token: ${{ secrets.VAULT_TOKEN }}
        cf_username: ${{ secrets.CF_USERNAME }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_domain: ${{ secrets.CF_DOMAIN }}
        paas_namespace: ${{ secrets.PAAS_NAMESPACE }}
        paas_env: ${{ secrets.dev }}
        paas_app_name: ${{ secrets.PAAS_APP_NAME }}
